services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=mydatabase
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123

  nodejs_app:
    build: .
    container_name: nodejs_app
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
    volumes:
      - .:/app

volumes:
  clickhouse_data:
    driver: local
